spring.datasource.url=jdbc:sqlite:./fireworks.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# 应用启动时是否初始化数据库 schema
fireworks.db.init-schema=true
# tushare 行情数据源
tushare.token=968c30ff5409dfa75d6ff856a8334ad9140820322b070c2d66d41ee8
tushare.base-url=https://api.tushare.pro
server.port=8080